import os
import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from flask import current_app


def _safe_name(value: str) -> str:
    sanitized = str(value or "Untitled Game").strip()
    cleaned = ''.join(ch if ch.isalnum() or ch in {'-', '_'} else '-' for ch in sanitized.lower())
    cleaned = cleaned.strip('-_')
    cleaned = re.sub(r'-{2,}', '-', cleaned)
    return (cleaned or 'untitled-game')[:60]


def _write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')


def generate_game_project(project) -> Path:
    root = Path(current_app.instance_path) / 'generated'
    root.mkdir(parents=True, exist_ok=True)

    safe_title = str(getattr(project, "title", "Untitled Game") or "Untitled Game").strip()
    if not safe_title:
        safe_title = "Untitled Game"

    project_slug = _safe_name(safe_title)
    project_dir = root / f"{project.id}-{project_slug}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
    project_dir.mkdir(parents=True, exist_ok=False)

    scenes_dir = project_dir / 'scenes'
    scripts_dir = project_dir / 'scripts'
    scenes_dir.mkdir(parents=True, exist_ok=True)
    scripts_dir.mkdir(parents=True, exist_ok=True)

    project_name = safe_title.replace('\n', ' ').replace('\r', ' ')
    gdproject = '''; Engine configuration file.
; It's best edited using the editor.

config_version=5

[application]
config/name="{title}"
run/main_scene="res://scenes/Main.tscn"

[rendering]
renderer/rendering_method="mobile"
'''.format(title=project_name)

    _write_text(project_dir / 'project.godot', gdproject)
    _write_text(project_dir / 'README.md', (
        f"# {project_name}\n\n"
        f"Generated by Prompt2Play for: {getattr(getattr(project, 'owner', None), 'username', 'guest')}\n\n"
        f"Objective: {project.objective}\n"
        f"Win condition: {project.win_condition}\n"
        f"Lose condition: {project.lose_condition}\n"
    ))

    main_scene = '''[gd_scene load_steps=2 format=3 uid="uid://main-scene"]

[ext_resource type="Script" path="res://scripts/Main.gd" id="1"]

[node name="Main" type="Node2D"]
script = ExtResource("1")
'''

    main_script = '''extends Node2D

var player_health = 100
var objective_text = "{objective}"

func _ready():
    print("Starting {title}...")
    print(objective_text)

func _process(delta):
    if player_health <= 0:
        print("Game over: {lose_condition}")
'''.format(title=project_name, objective=project.objective, lose_condition=project.lose_condition)

    _write_text(scenes_dir / 'Main.tscn', main_scene)
    _write_text(scripts_dir / 'Main.gd', main_script)

    project.project_dir = str(project_dir)
    return project_dir


def create_project_zip(project_dir: Path, output_dir: Path) -> Path:
    project_dir = project_dir.resolve()
    output_dir = output_dir.resolve()

    try:
        project_dir.relative_to(output_dir)
    except ValueError as exc:
        raise ValueError("Project directory must be created under the allowed export root.") from exc

    if project_dir == output_dir or not project_dir.is_dir():
        raise ValueError("Project directory must be a real directory under the export root.")

    zip_path = output_dir / f"{project_dir.name}.zip"
    output_dir.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for file_path in sorted(project_dir.rglob('*')):
            if file_path.is_file() and not file_path.is_symlink():
                archive.write(file_path, arcname=file_path.relative_to(project_dir))

    return zip_path
